version: "3.7"
services:
  rabbit:
    image: rabbitmq:latest

  fastapi:
    image: vivatranslatestaging/prod
    ports:
      - 80:80
    entrypoint: uvicorn main:router --host 0.0.0.0 --port 80

  worker:
    image: vivatranslatestaging/prod
    entrypoint: celery -A worker.celery_app worker --loglevel=info -c 2 -P threads
